# Generated by Django 4.0.6 on 2022-07-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/Galleries/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image_alt',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
