# Generated by Django 4.0.6 on 2022-07-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_variant_price_product_discount_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('new', 'New'), ('discount', 'Discount'), ('normal', 'Normal')], default='new', max_length=200),
        ),
    ]
